# Generated by Django 5.0.7 on 2024-07-16 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='chat_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages', to='chat.chatroom'),
        ),
    ]
